name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker images
        run: |
          for dir in src/*/; do
            project_name=$(basename "$dir")
            echo "Building Docker image for project: $project_name"
            docker build -t gcr.io/${{ secrets.PROJECT_ID }}/$project_name $dir
            docker push gcr.io/${{ secrets.PROJECT_ID }}/$project_name
          done

      - name: Deploy to Cloud Run
        run: |
          for dir in src/*/; do
            project_name=$(basename "$dir")
            echo "Deploying project: $project_name"
            gcloud run deploy $project_name --image=gcr.io/${{ secrets.PROJECT_ID }}/$project_name --platform=managed --region=us-central1 --allow-unauthenticated
          done